const linksArr = [
  {
    title: "New to Asana?",
    links: [
      ["Product overview", "/product"],
      ["All features", "/features"],
      ["Latest feature release", "/whats-new"],
      ["Pricing", "/pricing"],
      ["Starter plan", "/plan/starter"],
      ["Advanced plan", "/plan/advanced"],
      ["Enterprise", "/enterprise"],
      ["App integrations", "/apps"],
      ["AI work management", "/products/ai"],
      ["Project management", "/resources/benefits-project-management"],
      ["Resource management", "/resources/resource-management-plan"],
    ],
  },
  {
    title: "Use cases",
    links: [
      ["Campaign management", "/uses/campaign-management"],
      ["Content calendar", "/uses/content-calender"],
      ["Creative production", "/uses/creative-production"],
      ["Goal management", "/uses/goal-management"],
      ["New hire onboarding", "/uses/employee-onboarding"],
      ["Organizational planning", "/uses/organizational-planning"],
      ["Product launches", "/uses/product-launch"],
      ["Resource planning", "/uses/resource-planning"],
      ["Strategic planning", "/uses/marketing-strategic-planning"],
      ["Project intake", "/uses/project-intake"],
      ["All use cases", "/uses"],
    ],
  },
  {
    title: "Solutions",
    links: [
      ["Marketing", "/teams/marketing"],
      ["Operations", "/teams/operations"],
      ["IT", "/teams/operations"],
      ["Product", "/teams/product-manager"],
      ["Sales", "/teams/sales"],
      ["Healthcare", "/industry/healthcare"],
      ["Retail", "/industry/retail"],
      ["Education", "/education"],
      ["Nonprofits", "/industry/nonprofit"],
      ["All teams", "/teams"],
    ],
  },
  {
    title: "Resources",
    links: [
      ["Help Center", "/help/s/"],
      ["Get support", "/help/s/#chat"],
      ["Asana Academy", "/academy"],
      ["Certifications", "/certifications"],
      ["Forum", "/forum"],
      ["Resource hub", "/resources"],
      ["Product templates", "/templates"],
      ["Events", "/events"],
      ["Customer Success", "/customer-success"],
      ["Developers and API", "/developers-api"],
      ["Partners", "/partners"],
      ["Sitemap", "/site-map"],
    ],
  },
  {
    title: "Company",
    links: [
      ["About us", "/company"],
      ["Leadership", "/leadership"],
      ["Customers", "/customers"],
      ["Careers", "/jobs"],
      ["Inside Asana", "/inside-asana"],
      ["Culture", "/culture-and-belonging"],
      ["Press", "/press"],
      ["Investor relations", "/investors"],
      ["Trust and security", "/trust"],
      ["Privacy", "/privacy"],
      ["Supplier responsibility", "/terms/modern-slavery-statement"],
      ["Sustainability and ESG", "/esg"],
    ],
  },
];

export default linksArr;
